version: '3.8'
services:
  award_paper-php:
    container_name: award_paper-php
    build: ./.docker/php
    restart: on-failure
    ports:
      - "9000:9000"
    volumes:
      - ./app/:/var/www/html
  award_paper-nginx:
    container_name: award_paper-nginx
    image: nginx:latest
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/:/var/www/html
    ports:
      - "8085:80"
    restart: on-failure
    depends_on:
      - award_paper-php
  award_paper-db:
    container_name: award_paper-db
    image: postgres:latest
    restart: on-failure
    env_file:
      - ./.docker/db/.env
    ports:
      - "5432:5432"
    volumes:
      - award_paper-db:/var/lib/postgres
  award_paper-mercure:
    container_name: award_paper-mercure
    image: dunglas/mercure
    restart: on-failure
    environment:
      SERVER_NAME: ':80' # Uncomment the following line to disable HTTPS
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET:-!ChangeMeThisMercureHubJWTSecretKeyMe!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET:-!ChangeMeThisMercureHubJWTSecretKeyMe!}
      command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev # Uncomment the following line to enable the development mode
    ports:
      - ${MERCURE_LOCAL_PORT:-80}:80
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  award_paper-db:
    name: award_paper-db
    driver: local
  caddy_data:
  caddy_config: